export const mockObjects = [
  {
    slug: "mine-mine-mine",
    title: "Mine Mine Mine",
    publisher: "University of Johannesburg Press",
    date: "2023",
    tags: ["Poetry"],
    image: "/placeholder-book.jpg",
    x: 200,
    y: 100,
  },
  {
    slug: "keorapetse-kgositsile",
    title: "Keorapetse Kgositsile",
    publisher: "Africa World Press",
    date: "2020",
    tags: ["Books"],
    image: "/placeholder-book.jpg",
    x: 700,
    y: 600,
  },
  {
    slug: "home-is-where-the-music-is",
    title: "Home Is Where the Music Is",
    publisher: "Chimurenga",
    date: "2021",
    tags: ["Essay"],
    image: "/placeholder-book.jpg",
    x: 400,
    y: 1200,
  },
  {
    slug: "decolonizing-world-literature-through-orality",
    title: "Decolonizing World Literature Through Orality",
    publisher: "-",
    date: "2021",
    tags: ["Essay"],
    image: "/placeholder-book.jpg",
    x: 800,
    y: 1800,
  },
];